version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      # - db_data:/var/lib/postgresql/data
      - ./database/create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql:ro
    environment:
      POSTGRES_PASSWORD: foo
  graphql-engine:
    image: hasura/graphql-engine:v1.0.0-beta.6
    ports:
      - "8080:8080"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:foo@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an admin secret
      # HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
  web-server:
    image: nginx
    ports:
      - "3001:80"
    volumes:
      - ./client/build:/usr/share/nginx/html:ro
volumes:
  db_data: